env: local
listenPort: :1917

managementUrl: http://127.0.0.1:31905

dblist: 
  app:
    dbType: mysql
    dbUrl: krisman:maef0mei3uigh1U@tcp(127.0.0.1:30007)/dbbilling

  dashb:
    dbType: mysql
    dbUrl: krisman:maef0mei3uigh1U@tcp(127.0.0.1:30007)/dashboard?parseTime=True
  ocs:
    dbType: mysql
    dbUrl: krisman:d30f610eaa@tcp(127.0.0.1:3310)/ocs?parseTime=True
appName: AppName
JWTSecretKey: MyJwtSecretKey
useJWT: false
requestTimeout: 5
debugLevel: 4
concurrentWaitLimit: 10
maxConcurrentProcessData: 10
maxBodyLogLength: 2048 #characters

useRedis: false
useRedisSentinel: false
redisSentinel:
  masterName: mylocalmaster
  sentinelPassword:
  sentinelUrl: 
  - 127.0.0.1:26379
redis:
  redisUrl: 127.0.0.1:6379
  redisPassword:
  db: 0

log:
  filenamePrefix: ./log/backendbillingdashboard
  level: debug
